
alias l='ls -halF'

# git
alias ga='git a'
alias gaa='git aa'
alias gamend='git amend'
alias gap='git add --patch'
alias gb='git b'
alias gbr='git b -r'
alias gcm='git cm'
alias gcut='git cut'
alias gco='git co'
alias gcp='git cherry-pick'
alias gdiff='git diff'
alias gfetch='git fetch'
alias gl='git ll'
alias glfp='git lfp'
alias gmerge='git merge'
alias gpushcurrent='git pushcurrent'
alias gpullcurrent='git pullcurrent'
alias greset='git reset'
alias greflog='git reflog'
alias gs='git s'
alias gstash='git stash'
alias gundo='git reset --mixed HEAD~'
alias gwip='git c -am "WIP"'
alias gwipe='!git add -A && git commit -qm "WIPE SAVEPOINT" && git reset HEAD~1 --hard'
